# Generated by Django 4.1.7 on 2023-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(default='Registration number', max_length=30, unique=True, verbose_name='Registration number'),
        ),
    ]
