# Generated by Django 4.1.7 on 2023-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Registration number'),
        ),
    ]
