# Generated by Django 4.1.7 on 2023-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=18, verbose_name='Registration number')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('sir_middle_name', models.CharField(max_length=100, verbose_name='Sir plus middle name')),
                ('level', models.IntegerField(verbose_name='Year of study')),
                ('date_registered', models.DateField()),
                ('phone_nnumber', models.PositiveIntegerField(max_length=12)),
                ('place_of_residence', models.CharField(choices=[('CHIROMO', 'CHIROMO'), ('MAIN', 'MAIN'), ('HOME', 'HOME')], max_length=7)),
                ('group_number', models.PositiveBigIntegerField(max_length=2, null=True)),
            ],
        ),
    ]
