# Generated by Django 4.1.7 on 2023-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_remove_members_id_alter_members_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='phone_nnumber',
        ),
        migrations.AddField(
            model_name='members',
            name='phone_number',
            field=models.CharField(default='0720000000', max_length=12),
        ),
    ]
