# Generated by Django 4.1.7 on 2023-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_alter_member_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group_number',
            field=models.PositiveBigIntegerField(default=0, max_length=2),
        ),
    ]
