# Generated by Django 4.1.7 on 2023-04-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0009_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[(None, 'Choose   Gender'), ('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_residence',
            field=models.CharField(choices=[(None, 'Place of residence'), ('CHIROMO', 'CHIROMO'), ('MAIN', 'MAIN'), ('HOME', 'HOME')], max_length=7),
        ),
    ]
